name: Publish NPM Version Info

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  dispatch:
    if: github.repository == 'lyswhut/lx-music-mobile'
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: lyswhut/lx-music-mobile-version-info
          event-type: npm-release
